import type { ComponentDocument } from "@podo/spec";

export type CodegenTarget = "web" | "react" | "hono" | "native";

export interface GeneratedFile {
  path: string;
  contents: string;
}

export interface GenerateComponentFilesOptions {
  specs: ComponentDocument[];
  targets: CodegenTarget[];
  outDir?: string;
}

export interface ComponentTemplateContext {
  spec: ComponentDocument;
  exportName: string;
  tagName: string;
}

export type ComponentTemplate = (context: ComponentTemplateContext) => string;

export const generatedFileHeader =
  "/* This file is generated by @podo/codegen. Do not edit directly. */";

export const componentTemplates: Record<CodegenTarget, ComponentTemplate> = {
  web: ({ exportName, tagName }) =>
    [
      `export const ${exportName}ElementName = ${JSON.stringify(tagName)};`,
      `export function define${exportName}(): string {`,
      `  return ${exportName}ElementName;`,
      "}",
    ].join("\n"),
  react: ({ exportName }) =>
    [
      `export { ${exportName} } from "@podo/react";`,
      `export type { ${exportName}Props } from "@podo/react";`,
    ].join("\n"),
  hono: ({ exportName }) => `export { ${exportName} } from "@podo/hono";`,
  native: ({ exportName }) =>
    [
      `export { ${exportName} } from "@podo/native";`,
      `export type { Native${exportName}Props } from "@podo/native";`,
    ].join("\n"),
};

export function generateComponentFiles(options: GenerateComponentFilesOptions): GeneratedFile[] {
  const outDir = trimSlashes(options.outDir ?? "generated");
  const specs = [...options.specs].sort((a, b) => a.id.localeCompare(b.id));
  const targets = [...options.targets].sort((a, b) => a.localeCompare(b));
  const files: GeneratedFile[] = [];

  for (const target of targets) {
    for (const spec of specs) {
      if (!spec.targets[target]?.supported) {
        continue;
      }

      const exportName = toPascalCase(spec.id);
      const context: ComponentTemplateContext = {
        spec,
        exportName,
        tagName: `podo-${spec.id}`,
      };

      files.push({
        path: `${outDir}/${target}/${spec.id}.${target}.ts`,
        contents: `${generatedFileHeader}\n${componentTemplates[target](context)}\n`,
      });
    }
  }

  return files.sort((a, b) => a.path.localeCompare(b.path));
}

export function generateIndexFile(files: GeneratedFile[], outDir = "generated"): GeneratedFile {
  const base = trimSlashes(outDir);
  const exports = files
    .map((file) => file.path.replace(`${base}/`, "./").replace(/\.ts$/, ".js"))
    .sort()
    .map((path) => `export * from ${JSON.stringify(path)};`)
    .join("\n");

  return {
    path: `${base}/index.ts`,
    contents: `${generatedFileHeader}\n${exports}\n`,
  };
}

export function assertIdempotent(filesA: GeneratedFile[], filesB: GeneratedFile[]): void {
  const stableA = JSON.stringify(filesA, null, 2);
  const stableB = JSON.stringify(filesB, null, 2);
  if (stableA !== stableB) {
    throw new Error("Codegen output is not idempotent for the same inputs.");
  }
}

function toPascalCase(value: string): string {
  return value
    .split(/[-_]/g)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("");
}

function trimSlashes(value: string): string {
  return value.replace(/^\/+|\/+$/g, "");
}
